export const LOGIN = 'LOGIN'
export const ROOMS = 'ROOMS'
export const ROOMSCHECKOUT = 'ROOMSCHECKOUT'
export const ROOMSCHECKIN = 'ROOMSIN'
export const ROOMSDETAIL = 'ROOMSDETAIL'
export const ROOMSUPDATE = 'ROOMSUPDATE'
export const ROOMSDELETE = 'ROOMDELETE'
export const ROOMTYPE = 'ROOMTYPE'
export const ORDERS = 'ORDERS'
export const ADDROOM = 'ADDROOM'
export const CUSTOMER = 'CUSTOMER'
export const ADDCUSTOMER = 'ADDCUSTOMER'
export const DETAILCUSTOMER = 'DETAILCUSTOMER'
export const ORDER = 'ORDER'
export const ORDERCHECKOUT = 'ORDERCHECKOUT'
export const ORDERCHECKIN = 'ORDERCHECKIN'

